#%RAML 1.0 Trait

 queryParameters:
      number:
        required: true
        type: integer
        example: 2
      number1 :
        required: true
        type: integer
        example: 5

 responses:
      400:
        body:
          application/json:
            example:
              {
                "result" : " bad request "
              }
                    
      404:
       body:
         application/json:
           example:
            {
              "result" : " not found "
            }
      500:
       body:
         application/json:
          example:
            {
                 "result" : " not found "
             }